services:
  app:
    image: ${IMAGE_NAME}:latest
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      # ✅ Persist only necessary storage directories
      - storage-logs:/usr/share/nginx/html/storage/logs
      - storage-framework-cache:/usr/share/nginx/html/storage/framework/cache
      - storage-framework-sessions:/usr/share/nginx/html/storage/framework/sessions
      - storage-framework-views:/usr/share/nginx/html/storage/framework/views
      - storage-app-public:/usr/share/nginx/html/storage/app/public
    networks: [appnet]
    expose:
      - "9000"

  queue-worker:
    image: ${IMAGE_NAME}:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      IS_WORKER: "true"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - storage-logs:/usr/share/nginx/html/storage/logs
      - storage-framework-cache:/usr/share/nginx/html/storage/framework/cache
      - storage-framework-sessions:/usr/share/nginx/html/storage/framework/sessions
      - storage-framework-views:/usr/share/nginx/html/storage/framework/views
      - storage-app-public:/usr/share/nginx/html/storage/app/public
    networks: [appnet]

  nginx:
    image: nginx:1.27-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

      # ✅ Mount built Laravel code (read-only)
      - app_code:/usr/share/nginx/html:ro

      # ✅ Only mount public files (accessible to web)
      - storage-app-public:/usr/share/nginx/html/storage/app/public:ro

      # ❌ Removed storage-logs to avoid write errors (not needed by nginx)
    networks: [appnet]

  db:
    image: mysql:8.0.36
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u${DB_USERNAME} -p${DB_PASSWORD} || exit 1"]
      interval: 10s
      retries: 10
      timeout: 5s
    networks: [appnet]

volumes:
  app_code:
    external: false
  storage-logs:
  storage-framework-cache:
  storage-framework-sessions:
  storage-framework-views:
  storage-app-public:
  db-data:

networks:
  appnet:
    driver: bridge
