version: "3.9"

services:
  app:
    image: ${IMAGE_NAME:-yourdockerhubuser/laravel-api}:latest
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      # Persist (will be wiped each deploy by the Action as requested)
      - storage:/usr/share/nginx/html/storage
      - public:/usr/share/nginx/html/public
    networks: [appnet]
    expose:
      - "9000"

  queue-worker:
    image: ${IMAGE_NAME:-yourdockerhubuser/laravel-api}:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      IS_WORKER: "true"
    depends_on:
      - db
    volumes:
      - storage:/usr/share/nginx/html/storage
      - public:/usr/share/nginx/html/public
    networks: [appnet]

  nginx:
    image: nginx:1.27-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - public:/usr/share/nginx/html/public:ro
      - storage:/usr/share/nginx/html/storage:ro
    networks: [appnet]

  db:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    command: [
      "--default-authentication-plugin=mysql_native_password",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
      "--max_connections=300"
    ]
    networks: [appnet]

volumes:
  storage:
  public:
  db-data:

networks:
  appnet:
    driver: bridge
